# Generated by Django 4.0.2 on 2022-03-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_doctor_doctor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=25)),
                ('patient_dob', models.DateField()),
                ('patient_address', models.CharField(max_length=100)),
                ('patient_date_admitted', models.DateTimeField()),
            ],
        ),
    ]
