# Generated by Django 4.0.2 on 2022-03-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_patient_patient_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_date_admitted',
            field=models.DateField(),
        ),
    ]
