# Generated by Django 4.0.2 on 2022-02-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
